version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 4.1.1
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: font-awesome-rails
    versions:
    - 4.7.0.6
  - dependency-name: ffi
    versions:
    - 1.14.2
